[package]
name = "compile-typst-site"
repository = "https://github.com/wade-cheng/compile-typst-site/"
version = "0.1.2"
edition = "2024"

[dependencies]
error-iter = "0.4.1"
globset = "0.4.18"
log = "0.4.28"
notify-debouncer-full = "0.6.0"
onlyargs = "0.2.0"
onlyargs_derive = "0.2.0"
onlyerror = "0.1.5"
serde = { version = "1.0.228", features = ["derive"] } 
simple_logger = "5.1.0"
toml = "0.9.8"
walkdir = "2.5.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
